### ISSUE TITLE
Errores en la descripción del repositorio

### ISSUE THREAD

**Issue by JavierYuste** [scaverod/GamblingMarkovChain#5]
La descripción del repositorio es "Práctica realziadaen la asignatura de Métodos de Simulación del Master Universitario de Intligencia Artificial en el curso 2019/20.". Creo que debería ser "Práctica **realizada en** la asignatura de Métodos de Simulación del Master Universitario de **Inteligencia** Artificial en el curso 2019/20."

**Comment by scaverod** [comment]
Vale. Bien visto, lo cambio.
